FROM golang:1.27.2-alpine@sha256:f92b6ef800e499660581efdabdf25d9d817a9d124eaf900924f0504e7e27e12d AS build
WORKDIR /build
ENV CGO_ENABLED=0 GOMAXPROCS=2 GOMEMLIMIT=512MiB GOTOOLCHAIN=local
COPY infra/postgres/build/ ./
RUN go mod download && go build -mod=readonly -p 1 -trimpath -ldflags="-s -w -X main.Version=1.19" -o /gosu github.com/tianon/gosu

FROM postgres:16-alpine@sha256:721873c34ceb9f8d8fc265984940dc982404c105f19ad51be9fdc5970a6080ea
RUN apk add --no-cache zlib=1.3.2-r1
COPY --from=build /gosu /usr/local/bin/gosu
