FROM golang:1.27.2-alpine@sha256:f92b6ef800e499660581efdabdf25d9d817a9d124eaf900924f0504e7e27e12d AS build
WORKDIR /build
ENV CGO_ENABLED=0 GOMAXPROCS=2 GOMEMLIMIT=512MiB GOTOOLCHAIN=local
COPY infra/caddy/build/ ./
RUN go mod download && go build -mod=readonly -p 1 -trimpath -ldflags="-s -w" -o /caddy .
RUN go list -mod=readonly -deps . > /dependencies.txt && ! grep -q '^golang.org/x/crypto/openpgp' /dependencies.txt

FROM caddy:2-alpine@sha256:d8542f48d34a9cf4e4c11a478865229840e87e4c96ea3f439101f31a5d35f75f
RUN apk add --no-cache zlib=1.3.2-r1
COPY --from=build /caddy /usr/bin/caddy
